export default {
  translation: {
    // NOTE: The translations below were generated by ChatGPT and have not yet been verified.
    'Welcome! 🥳': 'مرحباً! 🥳',
    About: 'حول',
    'New Note': 'ملاحظة جديدة',
    Post: 'نشر',
    Home: 'الرئيسية',
    'Relay settings': 'إعدادات الريلاي',
    Settings: 'الإعدادات',
    SidebarRelays: 'الريلايات',
    Refresh: 'تحديث',
    Profile: 'الملف الشخصي',
    Logout: 'تسجيل الخروج',
    Following: 'المتابعون',
    followings: 'المتابعين',
    reposted: 'أُعيد نشره',
    'just now': 'الآن',
    'n minutes ago': 'منذ {{n}} دقيقة',
    'n m': '{{n}} دقيقة',
    'n hours ago': 'منذ {{n}} ساعة',
    'n h': '{{n}} ساعة',
    'n days ago': 'منذ {{n}} يوم',
    'n d': '{{n}} يوم',
    date: '{{timestamp, date}}',
    Follow: 'متابعة',
    Unfollow: 'إلغاء المتابعة',
    'Follow failed': 'فشل المتابعة',
    'Unfollow failed': 'فشل إلغاء المتابعة',
    'show new notes': 'إظهار الملاحظات الجديدة',
    'loading...': 'جار التحميل...',
    'no more notes': 'لا توجد ملاحظات إضافية',
    'reply to': 'الرد على',
    reply: 'رد',
    Reply: 'رد',
    'load more older replies': 'تحميل المزيد من الردود القديمة',
    'Write something...': 'اكتب شيئاً...',
    Cancel: 'إلغاء',
    Mentions: 'المنشنات',
    'Failed to post': 'فشل النشر',
    'Post successful': 'تم النشر بنجاح',
    'Your post has been published': 'تم نشر مشاركتك',
    Repost: 'إعادة النشر',
    Quote: 'اقتباس',
    'Copy event ID': 'نسخ معرف الحدث',
    'Copy user ID': 'نسخ معرف المستخدم',
    'View raw event': 'عرض الحدث الخام',
    Like: 'أعجبني',
    'switch to light theme': 'التبديل إلى الوضع الفاتح',
    'switch to dark theme': 'التبديل إلى الوضع الداكن',
    'switch to system theme': 'التبديل إلى وضع النظام',
    Note: 'ملاحظة',
    note: 'ملاحظة',
    "username's following": 'متابعي {{username}}',
    "username's used relays": 'الريلايات المستخدمة لـ {{username}}',
    "username's muted": '{{username}} تم كتمه',
    Login: 'تسجيل الدخول',
    'Follows you': 'يتابعك',
    'Relay Settings': 'إعدادات الريلاي',
    'Relay set name': 'اسم مجموعة الريلاي',
    'Add a new relay set': 'إضافة مجموعة ريلاي جديدة',
    Add: 'إضافة',
    'n relays': '{{n}} ريلايات',
    Rename: 'إعادة تسمية',
    'Copy share link': 'نسخ رابط المشاركة',
    Delete: 'حذف',
    'Relay already exists': 'الريلاي موجود بالفعل',
    'invalid relay URL': 'عنوان URL للريلاي غير صالح',
    'Add a new relay': 'إضافة ريلاي جديدة',
    back: 'عودة',
    'Lost in the void': 'ضائع في الفراغ',
    'Carry me home': 'أعدني إلى المنزل',
    'no replies': 'لا توجد ردود',
    'Reply to': 'الرد على',
    Search: 'بحث',
    'The relays you are connected to do not support search': 'الريلايات المتصلة لا تدعم البحث',
    'Show more...': 'عرض المزيد...',
    'All users': 'جميع المستخدمين',
    'Display replies': 'عرض الردود',
    Notes: 'الملاحظات',
    Replies: 'الردود',
    Notifications: 'الإشعارات',
    'no more notifications': 'لا توجد إشعارات إضافية',
    'Using private key login is insecure. It is recommended to use a browser extension for login, such as alby, nostr-keyx or nos2x.':
      'استخدام تسجيل الدخول بالمفتاح الخاص غير آمن. يُنصح باستخدام إضافة المتصفح مثل alby أو nostr-keyx أو nos2x.',
    'Login with Browser Extension': 'تسجيل الدخول باستخدام إضافة المتصفح',
    'Login with Bunker': 'تسجيل الدخول باستخدام Bunker',
    'Login with Private Key': 'تسجيل الدخول باستخدام المفتاح الخاص',
    'reload notes': 'إعادة تحميل الملاحظات',
    'Logged in Accounts': 'الحسابات المسجلة',
    'Add an Account': 'إضافة حساب',
    'More options': 'المزيد من الخيارات',
    'Add client tag': 'إضافة وسم العميل',
    'Show others this was sent via Jumble': 'عرض أن هذه الرسالة أُرسلت عبر Jumble',
    'Are you sure you want to logout?': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
    'relay sets': 'مجموعات الريلاي',
    edit: 'تعديل',
    Languages: 'اللغات',
    Theme: 'المظهر',
    System: 'النظام',
    Light: 'فاتح',
    Dark: 'داكن',
    Temporary: 'مؤقت',
    'Choose a relay set': 'اختر مجموعة ريلاي',
    'Switch account': 'تبديل الحساب',
    Pictures: 'الصور',
    'Picture note': 'ملاحظة الصورة',
    'A special note for picture-first clients like Olas':
      'ملاحظة خاصة للعملاء المعتمدين على الصور مثل Olas',
    'Picture note requires images': 'ملاحظة الصورة تتطلب صور',
    Relays: 'الريلايات',
    image: 'صورة',
    'R & W': 'قراءة وكتابة',
    Read: 'قراءة',
    Write: 'كتابة',
    'Pull relay sets': 'سحب مجموعات الريلاي',
    'Select the relay sets you want to pull': 'اختر مجموعات الريلاي التي تريد استلامها',
    'No relay sets found': 'لم يتم العثور على مجموعات ريلاي',
    'Pull n relay sets': 'سحب {{n}} مجموعات ريلاي',
    Pull: 'سحب',
    'Select all': 'اختر الكل',
    'Relay Sets': 'مجموعات الريلاي',
    'Read & Write Relays': 'ريلايات القراءة والكتابة',
    'read relays description':
      'تُستخدم ريلايات القراءة لاسترجاع الأحداث المتعلقة بك. ينشر المستخدمون الآخرون الأحداث التي ترغب في مشاهدتها إلى هذه الريلايات.',
    'write relays description':
      'تُستخدم ريلايات الكتابة لنشر أحداثك. يسترجع المستخدمون الآخرون أحداثك من هذه الريلايات.',
    'read & write relays notice': 'يُفضل أن يكون عدد خوادم القراءة والكتابة بين 2 و4.',
    "Don't have an account yet?": 'لا تملك حساباً بعد؟',
    'or simply generate a private key': 'أو ببساطة أنشئ مفتاحاً خاصاً',
    'This is a private key. Do not share it with anyone. Keep it safe and secure. You will not be able to recover it if you lose it.':
      'هذا مفتاح خاص. لا تشاركه مع أي أحد. احفظه بأمان، فلن تتمكن من استرجاعه إذا فقدته.',
    Edit: 'تعديل',
    Save: 'حفظ',
    'Display Name': 'اسم العرض',
    Bio: 'السيرة الذاتية',
    'Nostr Address (NIP-05)': 'عنوان Nostr (NIP-05)',
    'Invalid NIP-05 address': 'عنوان NIP-05 غير صالح',
    'Copy private key': 'نسخ المفتاح الخاص',
    'Enter the password to decrypt your ncryptsec': 'أدخل كلمة المرور لفك تشفير ncryptsec',
    Back: 'رجوع',
    'optional: encrypt nsec': 'اختياري: تشفير nsec',
    password: 'كلمة المرور',
    'Sign up': 'تسجيل',
    'Save to': 'حفظ إلى',
    'Enter a name for the new relay set': 'أدخل اسماً لمجموعة ريلاي جديدة',
    'Save to a new relay set': 'حفظ في مجموعة ريلاي جديدة',
    Mute: 'كتم',
    Muted: 'تم كتمه',
    Unmute: 'إلغاء الكتم',
    'Mute user': 'كتم المستخدم',
    'Unmute user': 'إلغاء كتم المستخدم',
    'Append n relays': 'إضافة {{n}} ريلايات',
    Append: 'إضافة',
    'Select relays to append': 'اختر الريلايات للإضافة',
    'calculating...': 'جار الحساب...',
    'Calculate optimal read relays': 'حساب أفضل ريلايات للقراءة',
    'Login to set': 'تسجيل الدخول للوصول إلى المجموعة',
    'Please login to view following feed': 'يرجى تسجيل الدخول لعرض خلاصات المتابعة',
    'Send only to r': 'إرسال فقط إلى {{r}}',
    'Send only to these relays': 'إرسال فقط إلى هذه الريلايات',
    Explore: 'استكشاف',
    'Search relays': 'البحث في الريلايات',
    relayInfoBadgeAuth: 'مصادقة',
    relayInfoBadgeSearch: 'بحث',
    relayInfoBadgePayment: 'دفع',
    Operator: 'المشغل',
    Contact: 'اتصال',
    Software: 'البرنامج',
    Version: 'الإصدار',
    'Random Relays': 'ريلايات عشوائية',
    randomRelaysRefresh: 'تحديث',
    'Explore more': 'استكشاف المزيد',
    'Payment page': 'صفحة الدفع',
    'Supported NIPs': 'NIPs المدعومة',
    'Open in a': 'فتح في {{a}}',
    'Cannot handle event of kind k': 'لا يمكن معالجة الحدث من النوع {{k}}',
    'Sorry! The note cannot be found 😔': 'عذراً! لا يمكن العثور على الملاحظة 😔',
    'This user has been muted': 'تم كتم هذا المستخدم',
    Wallet: 'المحفظة',
    Sats: 'Sats',
    sats: 'sats',
    'Zap to': 'إرسال Zap إلى',
    'Zap n sats': 'Zap {{n}} sats',
    zapComment: 'تعليق',
    'Default zap amount': 'الكمية الافتراضية لـ Zap',
    'Default zap comment': 'التعليق الافتراضي لـ Zap',
    'Lightning Address (or LNURL)': 'عنوان Lightning (أو LNURL)',
    'Quick zap': 'Zap سريع',
    'If enabled, you can zap with a single click. Click and hold for custom amounts':
      'إذا تم تمكينه، يمكنك إرسال Zap بنقرة واحدة. انقر واستمر للحصول على كميات مخصصة',
    All: 'الكل',
    Reactions: 'التفاعلات',
    Zaps: 'Zaps',
    'Enjoying Jumble?': 'هل تستمتع بـ Jumble؟',
    'Your donation helps me maintain Jumble and make it better! 😊':
      'تبرعك يساعد في صيانة Jumble وتحسينه! 😊',
    'Earlier notifications': 'الإشعارات السابقة',
    'Temporarily display this note': 'عرض هذه الملاحظة مؤقتاً',
    buttonFollowing: 'جارٍ المتابعة',
    'Are you sure you want to unfollow this user?':
      'هل أنت متأكد أنك تريد إلغاء متابعة هذا المستخدم؟',
    'Recent Supporters': 'الداعمين الجدد',
    'Seen on': 'شوهد على',
    'Temporarily display this reply': 'عرض هذا الرد مؤقتاً',
    'Not found the note': 'لم يتم العثور على الملاحظة',
    'no more replies': 'لا توجد مزيد من الردود',
    'Relay sets': 'مجموعات الريلاي',
    'Favorite Relays': 'الريلايات المفضلة',
    "Following's Favorites": 'المفضلات من المتابعين',
    'no more relays': 'لا توجد مزيد من الريلايات',
    'Favorited by': 'المفضلة من قبل',
    'Post settings': 'إعدادات النشر',
    'Media upload service': 'خدمة تحميل الوسائط',
    'Choose a relay': 'اختر ريلاي',
    'no relays found': 'لم يتم العثور على ريلايات',
    video: 'فيديو',
    'Show n new notes': 'عرض {{n}} ملاحظات جديدة',
    YouTabName: 'أنت',
    Bookmark: 'الإشارة المرجعية',
    'Remove bookmark': 'إزالة الإشارة',
    'no bookmarks found': 'لم يتم العثور على إشارات',
    'no more bookmarks': 'لا مزيد من الإشارات',
    Bookmarks: 'الإشارات المرجعية',
    'Show more': 'عرض المزيد',
    General: 'عام',
    Autoplay: 'التشغيل التلقائي',
    'Enable video autoplay on this device': 'تمكين التشغيل التلقائي للفيديو على هذا الجهاز',
    'Paste or drop media files to upload': 'الصق أو اسحب ملفات الوسائط لتحميلها',
    Preview: 'معاينة',
    'You are about to publish an event signed by [{{eventAuthorName}}]. You are currently logged in as [{{currentUsername}}]. Are you sure?':
      'أنت على وشك نشر حدث موقع من قبل [{{eventAuthorName}}]. أنت حالياً مسجل الدخول كـ [{{currentUsername}}]. هل أنت متأكد؟',
    'Platinum Sponsors': 'الرعاة البلاتينيون',
    From: 'من',
    'Comment on': 'تعليق على',
    'View on njump.me': 'عرض على njump.me',
    'Hide content from untrusted users': 'إخفاء المحتوى من المستخدمين غير الموثوقين',
    'Only show content from your followed users and the users they follow':
      'فقط عرض المحتوى من المستخدمين الذين تتابعهم والمستخدمين الذين يتابعونهم'
  }
}
